INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_DVBS2CORRELATOR dvbs2correlator)

FIND_PATH(
    DVBS2CORRELATOR_INCLUDE_DIRS
    NAMES dvbs2correlator/api.h
    HINTS $ENV{DVBS2CORRELATOR_DIR}/include
        ${PC_DVBS2CORRELATOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    DVBS2CORRELATOR_LIBRARIES
    NAMES gnuradio-dvbs2correlator
    HINTS $ENV{DVBS2CORRELATOR_DIR}/lib
        ${PC_DVBS2CORRELATOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DVBS2CORRELATOR DEFAULT_MSG DVBS2CORRELATOR_LIBRARIES DVBS2CORRELATOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(DVBS2CORRELATOR_LIBRARIES DVBS2CORRELATOR_INCLUDE_DIRS)

